feat: Improve BMR test coverage, BMR refactoring #399
icon-project/icon-bridge pull request #445
Opened 2022-09-08 15:20 UTC by andrii-kl

2022-09-15 01:40 UTC, CyrusVorwald-ICON commented
This is a very large number of changes to review. Can this be split it up into many smaller reviews?

2022-09-15 11:18 UTC, andrii-kl commented
> This is a very large number of changes to review. Can this be split it up into many smaller reviews?

Unfortunately the receiver file has high coupling code and a lot of connection with different components. 
I tried to minimize changes scope, so current PR doesn't have optional changes.

In the next steps I there is a plan to remove reciver_core, It will require some additional refactoring but should increase total code coverage a lot.

2022-09-20 10:33 UTC, bbist commented
Hi @andrii-kl,
There are a lot of changes. The full review might take some time. What I'll do is, make some changes and refactoring to fix minor issues and push the changes. Will need to run the end-to-end test before merging into main. If it works out, we can merge and start making modifications on top of that. I hope you'll be able to take up and continue this after SNOW integration. Even though the coverage might be high, it still needs to cover edge cases, that we can discuss once you start working on it next time.

2022-09-21 08:40 UTC, bbist requested changes

2022-09-21 11:22 UTC, manishbista28 commented on cmd/iconbridge/chain/icon/client.go
> +					case types.JsonrpcErrorCodePending, types.JsonrpcErrorCodeNotFound:
types.JsonrpcErrorCodeExecuting seems to be missing.

2022-09-22 08:25 UTC, andrii-kl commented on cmd/iconbridge/chain/icon/register_relay.go
> -package icon
I got it, I didn't find any use of this file, I thought it was unused.

2022-09-23 09:52 UTC, bbist commented
@andrii-kl, @manishbista28,

Are there any other issues that we want to push in current release? If there are, we need to merge them before this PR. Only then we should merge this PR.
I'd like to make this PR part of next release, because even though the test coverage percentage is high the actual tests don't include all critical paths. So, before releasing this PR we'd want to resolve all those issues.

2022-09-23 10:07 UTC, bbist commented
> @andrii-kl, @manishbista28, @pragyanshrestha-ibriz,
> 
> Are there any other issues that we want to push in current release? If there are, we need to merge them before this PR. Only then we should merge this PR. I'd like to make this PR part of next release, because even though the test coverage percentage is high the actual tests don't include all critical paths. So, before releasing this PR we'd want to resolve all those issues.

I'm approving this change as e2e test seems to be running fine. Any changes after this PR is merge into main should be made part of next release.

2022-09-23 10:08 UTC, bbist approved these changes

2022-09-23 10:25 UTC, merged

2022-10-14 07:51 UTC, andrii-kl commented
https://github.com/icon-project/icon-bridge/issues/614