feat(bts): Implement logging for event data as Json string
icon-project/icon-bridge pull request #458
Opened 2022-09-12 11:53 UTC by shreyasbhat0

2022-09-14 06:04 UTC, MuhammedIrfan requested changes

2022-09-14 06:04 UTC, MuhammedIrfan commented on rust/near/bsh/bts/src/coin_management.rs
> +                    "token_name":coin_name
```suggestion
                    "amount": amount,
                    "token_name": coin_name
```

2022-09-14 06:04 UTC, MuhammedIrfan commented on rust/near/bsh/bts/src/coin_management.rs
> +                    "token_name":coin_name
```suggestion
                    "amount": amount,
                    "token_name": coin_name
```

2022-09-14 06:04 UTC, MuhammedIrfan commented on rust/near/bsh/bts/src/messaging.rs
> +                        "amount":asset.amount(),
```suggestion
                        "amount": asset.amount(),
```

2022-09-14 06:04 UTC, MuhammedIrfan commented on rust/near/bsh/bts/src/messaging.rs
> +                      "event":"TransferStart",
```suggestion
                      "event": "TransferStart",
```

2022-09-14 06:04 UTC, MuhammedIrfan commented on rust/near/bsh/bts/src/messaging.rs
> +                      "assets":assets_log
```suggestion
                      "sender_address": sender,
                      "serial_number": serial_no,
                      "receiver_address": receiver,
                      "assets": assets_log
```

2022-09-14 06:04 UTC, MuhammedIrfan commented on rust/near/bsh/bts/src/messaging.rs
> +                        "amount":asset.amount(),
```suggestion
                        "amount": asset.amount(),
```

2022-09-14 06:04 UTC, MuhammedIrfan commented on rust/near/bsh/bts/src/accounting.rs
> +                    "token_name":coin_symbol
```suggestion
                    "by": account,
                    "amount": amount,
                    "token_name": coin_symbol
```

2022-09-14 06:04 UTC, MuhammedIrfan commented on rust/near/bsh/bts/src/coin_management.rs
> +                    "event":"Mint",
```suggestion
                    "event": "Mint",
```

2022-09-14 06:04 UTC, MuhammedIrfan commented on rust/near/bsh/bts/src/coin_management.rs
> +                    "event":"Burn",
```suggestion
                    "event": "Burn",
```

2022-09-14 06:04 UTC, MuhammedIrfan commented on rust/near/bsh/bts/src/coin_management.rs
> +                    "event":"Burn",
```suggestion
                    "event": "Burn",
```

2022-09-14 06:51 UTC, sanglt1902 commented
@MuhammedIrfan LGTM, can you help to deploy it ASAP and perform to transfer of some transactions?

2022-09-14 12:15 UTC, shreyasbhat0 reviewed
Changes has been made

2022-09-15 01:25 UTC, MuhammedIrfan commented on rust/near/bsh/bts/src/accounting.rs
> +                    "code": 0,
```suggestion
                    "code": 1,
```

2022-09-15 01:27 UTC, MuhammedIrfan commented on rust/near/bsh/bts/src/messaging.rs
> +                    log!(log.as_str().unwrap().to_string());
```suggestion
                    log!(log.as_str().unwrap());
```

2022-09-15 01:27 UTC, MuhammedIrfan commented on rust/near/bsh/bts/src/messaging.rs
> +                    log!(log.as_str().unwrap().to_string())
```suggestion
                    log!(log.as_str().unwrap())
```

2022-09-15 01:29 UTC, MuhammedIrfan approved these changes

2022-09-15 01:29 UTC, MuhammedIrfan commented
> @MuhammedIrfan LGTM, can you help to deploy it ASAP and perform to transfer of some transactions?

Sure

2022-09-15 01:39 UTC, MuhammedIrfan requested changes
Please fix the unit tests

2022-09-15 06:03 UTC, shreyasbhat0 commented
> Please fix the unit tests

this has been fixed.

2022-09-15 07:37 UTC, MuhammedIrfan approved these changes

2022-09-15 07:43 UTC, merged