Docs/add documentation
icon-project/icon-bridge pull request #547
Opened 2022-09-28 04:18 UTC by izyak

Closes #ISSUE-NUMBER

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have documented my code in accordance with the [documentation guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#documentation)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have run the unit tests
- [ ] I only have one commit (if not, squash them into one commit).
- [ ] I have a descriptive commit message that adheres to the [commit message guidelines](https://github.com/icon-project/community/blob/main/guidelines/technical/software-development-guidelines.md#commit-messages)

> Please review the [CONTRIBUTING.md](/CONTRIBUTING.md) file for detailed contributing guidelines.

2022-09-29 18:38 UTC, CyrusVorwald-ICON requested changes
Overall looks good.

The larger a PR, the longer it takes to merge to main. The requested changes impact some files, but others are ready to merge. However, they are all bundled so everything would be delayed together even though the files themselves are independent, and many can be merged as-is.

2022-09-29 18:38 UTC, CyrusVorwald-ICON commented on javascore/bts/README.md
> +## External Methods
API should be documented in code and then generated, not part of a README.

2022-09-29 18:38 UTC, CyrusVorwald-ICON commented on solidity/bmc/README.md
> +## API Documents
API should be documented in code and then generated, not part of a README.

2022-09-29 18:38 UTC, CyrusVorwald-ICON commented on solidity/bts/BTSCore.md
> +# BTS Core
API should be documented in code and then generated.

2022-09-29 18:38 UTC, CyrusVorwald-ICON commented on solidity/bts/BTSPeriphery.md
> +# BTSPeriphery
API should be documented in code and then generated.

2022-09-30 03:50 UTC, izyak commented on docs/codeql.md
> +# CodeQL Check
Okay, deleting it

2022-09-30 03:50 UTC, izyak commented on docs/coverage.md
> +# Test Coverage with Codecov
Okay, deleting it

2022-09-30 03:50 UTC, izyak commented on docs/developer-guidelines.md
> +# Developer Guidelines
Just meant this to group docs together, was not sure if it would be needed. deleting this too

2022-09-30 04:57 UTC, izyak commented on docs/getting-started.md
> +# Getting Started
We have a MAKEFILE, which calls method in shell script `build.sh`. The `docker`, `docker-compose` commands are in  `build.sh` file. 

For eg. `make buildnodes` calls this function of the script. Running just a make command would be much better than having to run docker commands on different directories for some specific tasks.
```sh
build_chain_nodes() {
    echo "Start building docker containers for bsc and icon nodes"
    #make -C ../../../ dist-javascore dist-sol iconbridge-image
	mkdir -p ./data/bsc/node1
    
    export DOCKER_DEFAULT_PLATFORM=linux/amd64
    cd ../../..
    echo "Build BSC"
    docker build --tag bsc-node ./devnet/docker/bsc-node --build-arg KEYSTORE_PASS=Perlia0
    echo "Build ICON"
    cd ./devnet/docker/goloop
    docker build --tag icon-bsc_goloop:latest .

    echo "Build Process Complete"
    echo "To run the blockchain nodes. Use command: make runnodes"
}
```

2022-09-30 11:40 UTC, izyak commented on docs/tests/bts-javascore-test.md
> +## Covered test cases
Got it. Will make this chang in another PR

2022-09-30 18:53 UTC, CyrusVorwald-ICON commented on docs/getting-started.md
> +# Getting Started
Understood, this is good as-is for now. I spoke with @bbist about improving our build process and we can revisit it after SNOW and ETH are deployed.

2022-09-30 18:53 UTC, CyrusVorwald-ICON commented on docs/tests/bts-javascore-test.md
> +## Covered test cases
Thanks. Please re-request a review from me once all these changes are complete.

2022-10-09 00:56 UTC, CyrusVorwald-ICON commented
Please re-submit for approval once this is ready for review.

2022-10-09 05:40 UTC, izyak commented
It's ready for review

2022-10-11 01:46 UTC, CyrusVorwald-ICON approved these changes
Approved. Thank you for this contribution.

2022-10-11 01:52 UTC, merged

2022-10-31 11:03 UTC, CyrusVorwald-ICON commented
@all-contributors please add @izyak for tests and docs